# FROM continuumio/anaconda3:2022.10-amazonlinux amazon vm
# FROM continuumio/anaconda3:2022.10
# FROM python:3.8-alpine
FROM python:3.8-slim
ENV BASE_PATH /opt/recommend
ENV MODEL_PATH /opt/model
VOLUME [$MODEL_PATH]



RUN pip install gensim==4.3.1 pandas==2.0.0 protobuf==4.21.8 nltk==3.8.1 
RUN pip install boto3==1.26.119 psycopg2-binary==2.9.6   peewee==3.16.2    
RUN pip install numpy==1.24.3 newspaper3k==0.2.8 bytetrade-recommend-model-sdk==0.0.14
COPY recommend/  $BASE_PATH/
# following save credentials in docker is not safe, in future we will remove it
COPY resources/credentials  /root/.aws/ 
RUN  cd $BASE_PATH && \
     pip install -e . 
CMD ["python","-u","/opt/recommend/schedule_task/schedule_task.py"]