name: Update Server

on:
    workflow_dispatch:

    push:
        branches:
            - "main"

jobs:
    update_server:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - uses: actions/setup-go@v2
              with:
                go-version: 1.18.3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}
            - name: Build the docker Docker image
              run: |
                    docker build . -f server/packaging/docker/alpine/Dockerfile --tag ghcr.io/above-os/rss-server-v1:latest
                    docker push ghcr.io/above-os/rss-server-v1:latest




