name: Update Server

on:
  workflow_dispatch:

#  push:
#    branches:
#      - "main"
#      - "dev_wrx"
#    tags:
#      - "v*"

jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest
      - name: Build the docker Docker image
        run: |
          docker build . -f Dockerfile.server --tag lovehunter9/rss-server:${{ steps.get-latest-tag.outputs.tag }}
          docker push lovehunter9/rss-server:${{ steps.get-latest-tag.outputs.tag }}
