name: Update SDK

on:
    workflow_dispatch:

    push:
        branches:
            - "main"

jobs:
    update_sdk:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

           - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}            
            - name: Build the docker Docker image
              run: |
                    docker build . -f Dockerfile.sdk --tag aboveos/rss-sdk:latest
                    docker push aboveos/rss-sdk:latest